### ISSUE TITLE
Internal Error (http://127.0.0.1:3333/dashboard/overview) after login

### ISSUE THREAD

**Issue by aadityaverma** [iggy-rs/iggy-web-ui#4]
... async eval (/Users/aditya/iggy-web-ui/node_modules/@sveltejs/kit/src/runtime/server/page/index.js:141:13)
TypeError: Expected a finite number, got string: 43788 KiB
    at Proxy.prettyBytes (file:///Users/aditya/iggy-web-ui/node_modules/pretty-bytes/index.js:68:9)
    at Module.bytesFormatter (/Users/aditya/iggy-web-ui/src/lib/utils/formatters/bytesFormatter.ts:7:10)
    at Module.statsMapper (/Users/aditya/iggy-web-ui/src/lib/domain/Stats.ts:67:14)
    at load (/Users/aditya/iggy-web-ui/src/routes/dashboard/overview/+page.server.ts:15:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Module.load_server_data (/Users/aditya/iggy-web-ui/node_modules/@sveltejs/kit/src/runtime/server/page/load_data.js:51:17)
    at async eval (/Users/aditya/iggy-web-ui/node_modules/@sveltejs/kit/src/runtime/server/page/index.js:141:13)
    
    
    Copilot says : "The error message indicates that there is a type error in the code. Specifically, it is expecting a finite number but receiving a string value.

To resolve this issue, you need to locate the code that is causing the error and fix the type mismatch. Based on the stack trace, it seems that the error is occurring in the `bytesFormatter.ts` file at line 7.

Open the `bytesFormatter.ts` file and check the code at line 7. Make sure that the value being passed to the `prettyBytes` function is a finite number. If it is a string, you can convert it to a number using the `parseInt` or `parseFloat` function.

Here's an example of how you can convert a string to a number in JavaScript:

```javascript
const value = parseInt(stringValue, 10); // Assuming the base is 10
```

After making the necessary changes, save the file and re-run the command `npm run dev -- --host --port 3333` to see if the error is resolved."

**Comment by Pawel-Zygmunt** [comment]
@aadityaverma thanks for reporting. Web ui need to catch up with Iggy server. I'll get on it this week

**Comment by marvin-hansen** [comment]
Error still around. See error log below.

`npm run dev


> iggy-web-ui@0.0.1 dev
> vite dev --port 3002



  VITE v4.5.2  ready in 488 ms

  ➜  Local:   http://localhost:3002/
  ➜  Network: use --host to expose
  ➜  press h to show help
RangeError: End Date is invalid
    at Proxy.intervalToDuration (/Users/marvin/RustroverProjects/iggy-web-ui/node_modules/date-fns/intervalToDuration/index.js:46:35)
    at Module.statsMapper (/Users/marvin/RustroverProjects/iggy-web-ui/src/lib/domain/Stats.ts:33:5)
    at load (/Users/marvin/RustroverProjects/iggy-web-ui/src/routes/dashboard/overview/+page.server.ts:15:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Module.load_server_data (/Users/marvin/RustroverProjects/iggy-web-ui/node_modules/@sveltejs/kit/src/runtime/server/page/load_data.js:51:17)
    at async eval (/Users/marvin/RustroverProjects/iggy-web-ui/node_modules/@sveltejs/kit/src/runtime/server/page/index.js:141:13)`

**Comment by spetz** [comment]
Fixed with the recent UI changes & server's API serialization improvements.
